# syntax=docker/dockerfile:1

FROM eclipse-temurin:21-jdk AS build
WORKDIR /workspace

COPY .mvn/ .mvn/
COPY mvnw pom.xml ./
RUN chmod +x mvnw
RUN ./mvnw dependency:go-offline

COPY src/ src/
RUN ./mvnw package -Dmaven.test.skip

FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=build /workspace/target/{{ app_jar }} app.jar
EXPOSE {{ spring_http_port }}

ENTRYPOINT ["java","-jar","/app/app.jar"]
